name: Test HTML and CSS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install HTML and CSS linters
        run: |
          npm install htmlhint stylelint stylelint-config-standard --save-dev

      - name: Run HTML validation
        run: npx htmlhint '**/*.html'

      - name: Run CSS validation
        run: npx stylelint '**/*.css'

      - name: Display validation results
        run: echo "HTML and CSS validation completed"
